version: '3.7'

services:
  broker:
    image: rabbitmq:3.9-management
    container_name: services_broker
    environment:
      - RABBITMQ_DEFAULT_USER=broker_user
      - RABBITMQ_DEFAULT_PASS=broker_pass
      - RABBITMQ_DEFAULT_VHOST=alegra
    networks:
      - default

networks:
    default:
        driver: bridge
        name: alegra-network
        external: true
