version: '3.7'

services:
  broker:
    image: rabbitmq:3.9-alpine
    container_name: services_broker
    environment:
      - RABBIT_DEFAULT_USER=broker_user
      - RABBIT_DEFAULT_PASS=broker_pass
    networks:
      - default

networks:
    default:
        driver: bridge
        name: alegra-network
        external: true

